services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..  # Поднимаемся на уровень выше
      dockerfile: docker/backend.Dockerfile  # Указываем относительный путь
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ..  # Поднимаемся на уровень выше
      dockerfile: docker/frontend.Dockerfile  # Указываем относительный путь
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data: